contacto/urls.py
from django.urls import path
from .views import contact

urlpatterns = [
    path("", contact, name="contact"),
]

grafotec/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from inicio import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.inicio, name='home'),
    path('noticias/', include('noticias.urls')),
    path('nosotros/', include('nosotros.urls')),
    path('contactanos/', include('contacto.urls')),
    path('servicios/', include('servicios.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nosotros/urls.py
from django.urls import path
from .views import about

urlpatterns =  [
    path("", about, name='about'),
]

noticias/urls.py
from django.urls import path
from .views import render_posts, post_detail

app_name = "blog"

urlpatterns = [
    path("", render_posts, name="post"),
    path("<int:post_id>", post_detail, name="post_detail"),
]

servicios/urls.py
from django.urls import path
from .views import servicio, corporativa, packag, publicidad, giganto, digital

urlpatterns = [
    path("", servicio, name='servicio'),
    path("corporativa/", corporativa, name='corporativa'),
    path("giganto/", giganto, name='giganto'),
    path("packaging/", packag, name='packag'),
    path("publicidad/", publicidad, name='publicidad'),
]

contacto/models.py
from django.db import models

inicio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField


class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to="inicio/images/")
    url = URLField(blank=True)

noticias/models.py
from django.db import models
import datetime

class Notice(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=300)
    image = models.ImageField(upload_to="noticias/images")
    date = models.DateField(datetime.date.today)

servicios/models.py
from django.db import models

# Create your models here.

contacto/views.py
from django.shortcuts import render

def contact (request):
    return render(request, 'contactanos.html')

inicio/views.py
from django.shortcuts import render
from .models import Project


def inicio(request):
    projects = Project.objects.all()

    # muy pendiente con la variable que esta entre comilla 'projects'
    return render(request, "home.html", {"projects": projects})

nosotros/views.py
from django.shortcuts import render

def about (request):
    return render(request, 'about.html')

noticias/views.py
from django.shortcuts import render, get_object_or_404
from .models import Notice
 #mirar las variables nuevamente
def render_posts(request):
    posts = Notice.objects.all()
    return render(request, 'publicado.html', {'posts': posts})

def post_detail(request, post_id):
    post = get_object_or_404(Notice, pk=post_id)
    return render(request, 'publicaciones.html', {"post": post})

servicios/views.py
from django.shortcuts import render

def servicio (request):
    return render(request, 'servicio.html')

def corporativa (request):
    return render(request, 'corporativa.html')

def giganto (request):
    return render(request, 'giganto.html')

def publicidad (request):
    return render(request, 'publicidad.html')

def packag (request):
    return render(request, 'packaging.html')

def digital (request):
    return render(request, 'digital.html')

contacto/templates/contactanos.html
{% extends 'layout.html'%}
{% load static %}

{% block content %}

<div class="hola">
    <div class="imar">
        <img src="{% static 'images/BGRAFOTECXS.png' %}" alt="" width="100%" height="550px">
    </div>
</div>

{% include 'partials/form.html' %}

{% endblock %}

inicio/templates/home.html
{% extends 'layout.html'%}
{% load static %}

{% block content %}

{% include 'partials/banner.html' %}

<!-- zona de noticias -->
<div class="smallimg">
    <img src="{% static 'images/BANNERINFERIOR.png' %}" alt="banner pequeno" width="100%" height="200px">
    <h4 class="banner2-text">Servicio de impresiones Gráficas. Más de 12 años brindando <br> soluciones para alcanzar tus objetivos.</h4>
</div>

<div class="my-5 info">
    <h4 class="solutio1">NUESTROS SERVICIOS</h4>
</div>

<div class="contenedor-cards container my-4">
    <div class="card" style="width: 330px;">
        <img src="{% static 'images/SERVICIOPUBLICITARIO.png' %}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Impresiones Publicitarias</h5>
            <p class="card-subtitle">Materiales de gran importancia para lograr objetivos de venta y posicionamiento de marca.</p>
        </div>
    </div>
    <div class="card" style="width: 330px;">
        <img src="{% static 'images/SERVICIOCORPORATIVO.png' %}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Impresiones Corporativas</h5>
            <p class="card-subtitle">Herramientas que brindan orden y coherencia en la presentación de la identidad corporativa.</p>
        </div>
    </div>
    <div class="card" style="width: 330px;">
        <img src="{% static 'images/PACKAGINGECOLOGICO.png' %}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Packaging Ecológicos</h5>
            <p class="card-subtitle">Brindan protección al producto y permite expresar la identidad de la marca.</p>
        </div>
    </div>
</div>

<div class="clientes-img1 my-5">
    <img src="{% static 'images/PORQUENOSOTROS.png' %}" alt="cliente" width="100%">
</div>

<div class="clientes-img my-4">
    <h4 class="solutio1">PRINCIPALES SOCIOS</h4>
    <img src="{% static 'images/CLIENTES.png' %}" alt="cliente">
</div>


{% endblock %}

inicio/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Grafotec</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
    <link rel="shortcut icon" href="{% static 'images/logo-pesta.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fontawesome/css/fontawesome.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fontawesome/css/brands.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fontawesome/css/solid.css' %}">
</head>

<body>

    {% include 'partials/header.html' %}

    {% include 'partials/navbar.html' %}

    <div class="">
        <a href="whatsapp://send?phone=+51942236110text=Hola, ¿en que te puedo ayudar?" class="btn-wsp" target="_blank">
            <i class="fa-brands fa-whatsapp"></i>
        </a>
    </div>

    {% block content %}
    {% endblock %}

    {% include 'partials/footer.html' %}

    <script src="{% static 'scripts/scrollreveal.js' %}"></script>
    <script src="{% static 'main.js' %}"></script>

</body>

</html>

inicio/templates/partials/banner.html
{% load static %}

<div class="banner">
    <div class="banner-images-container">
        <img src="{% static 'images/BannerN2XS.png' %}" alt="uahsdfksads" width="100%" height="700px">
        <img src="{% static 'images/BannerN3XS.png' %}" alt="uahsdfksads"
        width="100%" height="700px">
        <img src="{% static 'images/BannerN4XS.png' %}" alt="uahsdfksads"
        width="100%" height="700px">
    </div>
    <div class="banner-text-container">
        <h2 class="banner-text">DEJA TODO EN <br> NUESTRAS MANOS</h2>
        <p class="banner-subtext">Nos encargamos de principio a fin <br> en la realización de tus proyectos</p>
        <a href="{% url 'servicio' %}" class="btn">CONSIGUE UNA COTIZACIÓN</a>
    </div>
</div>

inicio/templates/partials/footer.html
{% load static %}

<footer class="pie-pagina">
    <div class="grupo-1">
        <div class="box1">
            <figure>
                <a>
                    <img src="{% static 'images/logob.png' %}" alt="logo grafotec" width="150" height="100">
                    <!-- <p>Soluciones Gráficas Integrales</p> -->
                </a>
            </figure>
        </div>
        <div class="box">
            <h4>CONTACTO</h4>
            <a href="mailto:ventas@grafotecsac.com">ventas@grafotecsac.com</a>
            <!-- <p>942236110 / 975456799</p> -->
        </div>
        <div class="box">
            <h4>OFICINA CENTRAL</h4>
            <!-- <p>Jr. General Obergoso 271 <br>Of. 618 - Breña</p> -->

        </div>
        <div class="box">
            <h4>HORARIO DE ATENCIÓN</h4>
            <p>Lunes a viernes<br>09:00 am a 06:00 pm</p>
            <p>Sabados <br> 09:00 am a 02:00 pm</p>
        </div>
        <div class="box">
            <div class="red-social">
                <a href="https://www.facebook.com/profile.php?id=100057802173684" class="fa-brands fa-facebook"></a>
                <a href="whatsapp://send?phone=+51942236110text=Hola, ¿en que te puedo ayudar?"
                    class="fa-brands fa-whatsapp"></a>
                <a href="mailto:ventas@grafotecsac.com" class="fa-solid fa-envelope"></a>
                <a href="https://www.instagram.com/grafotec_sac/?next=%2Faccounts%2Fsignup%2F"
                    class="fa-brands fa-instagram"></a>
            </div>
        </div>
    </div>
    <div class="grupo-2">
        <small>&copy; 2023 <b>GRAFOTECSAC</b> - Todos los Derechos Reservados</small>
    </div>
</footer>

inicio/templates/partials/form.html
{% load static %}

<div class="clientes-img">
    <h4 class="solutio1">Solicite una cotización</h4>
</div>
<div class="my-5 formulario">
    <div class="contact-form">
        <form 
            action="https://formspree.io/f/xoqzdwvz"
            method="POST">
            <div class="form-group">
                <label for="nombre">Nombre:</label>
                <input type="text" id="nombre" name="nombre">
            </div>
            <div class="form-group">
                <label for="email">Correo:</label>
                <input type="email" id="email" name="email">
            </div>
            <div class="form-group2">
                <label for="telefono">Teléfono:</label>
                <input type="tel" id="telefono" name="telefono">
            </div>
            <div class="form-group2">
                <label for="empresa">Empresa:</label>
                <input type="text" id="empresa" name="empresa">
            </div>
            <div class="form-group3">
                <label for="mensaje" class="mensaje">Mensaje:</label>
                <textarea id="mensaje" name="mensaje"></textarea>
            </div>
            <button type="submit">Enviar</button>
        </form>
    </div>
</div>

inicio/templates/partials/header.html
{% load static %}

<div class="cabezera container">
    <div class="caja-1">
        <a href="{% url 'home' %}" class="head-img"><img src="{% static 'images/logoa.png'%}" width="150" height="100"></a>
        <!-- <div class="iconos2">
            <a href="tel:+51942236110" class="fa-solid fa-phone"></a>
            <p class="num">942236110 <br> 975456799 </p>
            <a href="mailto:ventas@grafotecsac.com" class="fa-solid fa-envelope"></a>
            <p class="correo">ventas@grafotecsac.com</p>
        </div> -->
        <div class="iconos">
            <a href="https://www.facebook.com/profile.php?id=100057802173684" class="fa-brands fa-facebook"></a>
            <a href="https://www.instagram.com/grafotec_sac/?next=%2Faccounts%2Fsignup%2F" class="fa-brands fa-instagram"></a>
            <a href="whatsapp://send?phone=+51942236110text=Hola, ¿en que te puedo ayudar?" class="fa-brands fa-whatsapp"></a>
        </div>
    </div>
</div>

inicio/templates/partials/navbar.html
{% load static %}

<div class="contenedor">
  <div class="menu-btn">
    <li class="fas fa-bars"></li>
  </div>
  <nav class="navbar">
    <a href="{% url 'home' %}" class="nav-link">Inicio</a>
    <a href="{% url 'about' %}" class="nav-link">Compañia</a>
    <a href="{% url 'servicio' %}" class="nav-link">Servicios</a>
    <a href="{% url 'contact'%}" class="nav-link">Contactanos</a>
  </nav>
</div>

nosotros/templates/about.html
{% extends 'layout.html'%}
{% load static %}

{% block content %}

<div>
    <div class="Contactenos-te">
        <img src="{% static 'images/NOSOTROSBANNER2B.webp' %}" alt="informacion" width="100%" height="600px">
    </div>
</div>

<div class="smallimg">
    <img src="{% static 'images/BANNERINFERIOR.png' %}" alt="banner pequeno" width="100%" height="200px">
    <h4 class="banner2-text">Nos comprometemos en brindar soluciones efectivas, <br> su satisfacción y tranquilidad son nuestra prioridad.</h4>
</div>

<div class="clientes-img1 my-5">
    <h4>NUESTROS VALORES FUNDAMENTALES</h4>
    <img src="{% static 'images/PORQUENOSOTRONEGRITA.webp' %}" alt="cliente" width="100%">
</div>

<div class="text0">
    <div class="text1 container">
        <p>Somos una empresa dedicada a brindar servicios en todo lo relacionado al campo de la impresión y diseño, contamos con más de 12 años de experiencia creando soluciones gráficas a medida. Durante años, hemos trabajado en conjunto con clientes de distintos sectores proporcionando servicios personalizados que cumplan con sus exigencias. Nuestro equipo está conformado por especialistas en cada campo del proceso de producción:<br><br> -Diseño <br> -Pre-prensa <br> -Prensa <br> -Post-prensa <br><br> Desde pequeños proyectos hasta grandes producciones en volumen, nos esforzamos por brindar servicios que se ajusten a sus necesidades.</p>
    </div>
    <div class="cards1">
        <div class="card1">
            <img src="{% static 'images/VISION.webp' %}" alt="Imagen 1">
            <h4>VISIÓN</h4>
            <p>Liderazgo en la evolución del sector gráfico, <br> que nos permita la innovación constante.</p>
        </div>
        <div class="card1">
            <img src="{% static 'images/MISION.webp' %}" alt="Imagen 2">
            <h4>MISIÓN</h4>
            <p>Brindar a nuestros clientes el mejor servicio que <br> genere valor y sume a su desarrollo.</p>
        </div>
        <div class="card1">
            <img src="{% static 'images/VALORES.webp' %}" alt="Imagen 3">
            <h4>VALORES</h4>
            <p>Honestidad, compromiso y sostenibilidad.</p>
        </div>
    </div>
</div>
{% endblock %}

noticias/templates/publicaciones.html
{% extends 'layout.html'%}

<h1>noticias</h1>

{% for notice in posts %}

<h2>{{posts.title}}</h2>
<p>{{posts.description|striptags|truncatechars:100}}</p>

<img src="{{posts.image.url}}" alt="{{posts.title}}">

<a href="{% url 'blog:post_detail' post.id %}">{{notice.title}}</a>

{% endfor%}

noticias/templates/publicado.html
{% extends 'layout.html' %}

<h1>post</h1>

<h2>{{notice.title}}</h2>
<h3>{{notice.date}}</h3>
<p>{{notice.description}}</p>
<img src="{{notice.image.url}}" alt="{{notice.title}}">

servicios/templates/corporativa.html
{% extends 'layout.html'%}
{% load static %}

{% block content %}

<h1 class="Contactenos-et">IMPRESIONES CORPORATIVAS</h1>
<p class="contactenos-text">Son Herramientas muy importantes que nos ayudan en la comunicación brindando orden e
    identidad corporativa, por ello contamos con una amplio conocimiento en su elaboración.</p>
<div class="contenedor-cards1 container my-4">
    <div class="card1" style="width: 25rem;">
        <img src="{% static 'images/agendaXS.png'%}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Agendas</h5>
        </div>
    </div>
    <div class="card1" style="width: 25rem;">
        <img src="{% static 'images/blocknotasXS.png'%}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Block de Notas</h5>
        </div>
    </div>
    <div class="card1" style="width: 25rem;">
        <img src="{% static 'images/membretadoXS.png'%}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Hojas Membretadas</h5>
        </div>
    </div>
    <div class="card1" style="width: 25rem;">
        <img src="{% static 'images/carpetasXS.png'%}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Sobres y Carpetas</h5>
        </div>
    </div>
    <div class="card1" style="width: 25rem;">
        <img src="{% static 'images/formatosXS.png'%}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Formatos de Control</h5>
        </div>
    </div>
    <div class="card1" style="width: 25rem;">
        <img src="{% static 'images/documentosinXS.png'%}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Documentos Internos</h5>
        </div>
    </div>
    <div class="card1" style="width: 25rem;">
        <img src="{% static 'images/tarjetaXS.png'%}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Tarjetas Personales</h5>
        </div>
    </div>
</div>

<div class="bann-cont">
    <div class="cont1"><a href="{% url 'publicidad' %}"><img src="{% static 'images/publi@XS.png'%}" alt="asdas"
                height="200px"></a>
    </div>

    <div class="cont1"><a href="{% url 'giganto' %}"><img src="{% static 'images/minigigaXS.png'%}" alt="asdas"
                height="200px"></a>
    </div>
    <div class="cont1"><a href="{% url 'packag' %}"><img src="{% static 'images/miniecologicoXS.png'%}" alt="asdas"
                height="200px"></a>
    </div>
</div>

{% endblock %}

servicios/templates/giganto.html
{% extends 'layout.html'%}
{% load static %}

{% block content %}

<h4 class="Contactenos-et">GIGANTOGRAFÍAS</h4>
<p class="contactenos-text">Nos permiten una mayor visibilidad de marca y atención del público por ser de gran formato, <br> su elaboración amerita diseños de gran calidad por ello utilizamos maquinaria <br> de alta tecnología en su producción.</p>
<div class="contenedor-cards1 container my-4">
    <div class="card1" style="width: 25rem;">
        <img src="{% static 'images/bannerXS.png'%}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Roll Screen</h5>
        </div>
    </div>
    <div class="card1" style="width: 25rem;">
        <img src="{% static 'images/LonaspXS.png'%}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Lonas Publicitarias</h5>
        </div>
    </div>
    <div class="card1" style="width: 25rem;">
        <img src="{% static 'images/vinilXS.png'%}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Vinilos</h5>
        </div>
    </div>
    <div class="card1" style="width: 25rem;">
        <img src="{% static 'images/altotransitoXS.png'%}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Vinil de Alto Tránsito</h5>
        </div>
    </div>
</div>

<div class="bann-cont">
    <div class="cont1"><a href="{% url 'publicidad' %}"><img src="{% static 'images/publi@XS.png'%}" alt="asdas" height="200px"></a>
    </div>
    <div class="cont1"><a href="{% url 'corporativa' %}"><img src="{% static 'images/minicorporXS.png'%}" alt="asdas" height="200px"></a>
    </div>
    <div class="cont1"><a href="{% url 'packag' %}"><img src="{% static 'images/miniecologicoXS.png'%}" alt="asdas" height="200px"></a>
    </div>
</div>

{% endblock %}

servicios/templates/packaging.html
{% extends 'layout.html'%}
{% load static %}

{% block content %}

<h4 class="Contactenos-et">PACKAGING ECOLÓGICOS</h4>
<p class="contactenos-text">Brindan protección al producto y expresan identidad de la marca, <br> por ello contamos con
    personal especializado.</p>
<div class="contenedor-cards1 container my-4">
    <div class="card1" style="width: 25rem;">
        <img src="{% static 'images/envasecartonXS.png'%}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Envases de Cartón Corrugado y Microcorrugado</h5>
        </div>
    </div>
    <div class="card1" style="width: 25rem;">
        <img src="{% static 'images/bolsacompraXS.png'%}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Bolsas de Compras en Material Reciclable</h5>
        </div>
    </div>
    <div class="card1" style="width: 25rem;">
        <img src="{% static 'images/notexXS.png'%}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Bolsas de Notex</h5>
        </div>
    </div>
    <div class="card1" style="width: 25rem;">
        <img src="{% static 'images/krafXS.png'%}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Bolsas de Papel Kraft</h5>
        </div>
    </div>
    <div class="card1" style="width: 25rem;">
        <img src="{% static 'images/cajapizaXS.png'%}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Cajas de Pizza</h5>
        </div>
    </div>
    <div class="card1" style="width: 25rem;">
        <img src="{% static 'images/cajasenvioXS.png'%}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Cajas de Envío</h5>
        </div>
    </div>
    <div class="card1" style="width: 25rem;">
        <img src="{% static 'images/cartonXS.png'%}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Envases de Cartón</h5>
        </div>
    </div>
</div>

<div class="bann-cont">
    <div class="cont1"><a href="{% url 'publicidad' %}"><img src="{% static 'images/publi@XS.png'%}" alt="asdas" height="200px"></a>
    </div>
    <div class="cont1"><a href="{% url 'corporativa' %}"><img src="{% static 'images/minicorporXS.png'%}" alt="asdas"
                height="200px"></a>
    </div>
    <div class="cont1"><a href="{% url 'giganto' %}"><img src="{% static 'images/minigigaXS.png'%}" alt="asdas"
                height="200px"></a>
    </div>
</div>

{% endblock %}

servicios/templates/publicidad.html
{% extends 'layout.html'%}
{% load static %}

{% block content %}

<h4 class="Contactenos-et">IMPRESIONES PUBLICITARIAS</h4>
<p class="contactenos-text">En GRAFOTEC nos hemos especializado en la elaboración de material publicitario, <br> siendo herramientas importantes para cumplimiento de objetivos <br> de toda compañía.</p>
<div class="contenedor-cards1 container my-4">
    <div class="card1" style="width: 25rem;">
        <img src="{% static 'images/RevistaXS.png'%}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Catálogos</h5>
        </div>
    </div>
    <div class="card1" style="width: 25rem;">
        <img src="{% static 'images/BroshureXS.png'%}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Brochure</h5>
        </div>
    </div>
    <div class="card1" style="width: 25rem;">
        <img src="{% static 'images/CatalogosXS.png'%}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Folletos</h5>
        </div>
    </div>
    <div class="card1" style="width: 25rem;">
        <img src="{% static 'images/TripticosXS.png'%}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Tripticos, Dipticos, Flyer</h5>
        </div>
    </div>
    <div class="card1" style="width: 25rem;">
        <img src="{% static 'images/popXS.png'%}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Material pop</h5>
        </div>
    </div>
    <div class="card1" style="width: 25rem;">
        <img src="{% static 'images/adhesivosXS.png'%}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Adhesivos</h5>
        </div>
    </div>
    <div class="card1" style="width: 25rem;">
        <img src="{% static 'images/rompetraficoXS.png'%}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Rompetrafico</h5>
        </div>
    </div>
    <div class="card1" style="width: 25rem;">
        <img src="{% static 'images/merchXS.png'%}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Merchandising</h5>
        </div>
    </div>
</div>

<div class="bann-cont">
    <div class="cont1"><a href="{% url 'corporativa' %}"><img src="{% static 'images/minicorporXS.png'%}" alt="asdas"></a>
    </div>
    <div class="cont1"><a href="{% url 'giganto' %}"><img src="{% static 'images/minigigaXS.png'%}" alt="asdas"></a>
    </div>
    <div class="cont1"><a href="{% url 'packag' %}"><img src="{% static 'images/miniecologicoXS.png'%}" alt="asdas"></a>
    </div>
</div>

{% endblock %}

servicios/templates/servicio.html
{% extends 'layout.html'%}
{% load static %}

{% block content %}

<div class="my-5 servicio">
    <h4 class="descripcion1">NUESTROS SERVICIOS</h4>
    <div class="service-et"><a href="#"><img src="{% static 'images/publiXS.png'%}" alt="asdas" height="300px">
            <p class="service-text">IMPRESIONES PUBLICITARIAS</p>
        </a>
    </div>
    <div class="service-et">
        <a href="#"><img src="{% static 'images/coopXS.png'%}" alt="asdas"
                height="300px">
            <p class="service-text2">IMPRESIONES CORPORATIVAS</p>
        </a>
    </div>
    <div class="service-et">
        <a href="#"><img src="{% static 'images/gigaXS.png'%}" alt="asdas" height="300px">
            <p class="service-text3">GIGANTOGRAFÍAS</p>
        </a>
    </div>
    <div class="service-et">
        <a href="#"><img src="{% static 'images/packXS.png'%}" alt="asdas"
                height="300px">
            <p class="service-text4">PACKAGING ECOLÓGICO</p>
        </a>
    </div>
</div>

{% endblock %}